package com.socialred2025.identity.application.dto;

public enum PermissionType {
    EDIT_PROFILE,
    CREATE_POST,
    COMMENT_ON_POSTS,
    LIKE_POSTS,
    FOLLOW_USERS,
    SEND_ACCEPT_FRIEND_REQUESTS,
    EDIT_DELETE_USER_PROFILES,
    BLOCK_SUSPEND_ACCOUNTS,
    DELETE_ANY_POSTS_COMMENTS
}
