server:
  port: 443

spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**

        - id: internal-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/internal/users/**

        - id: publications-service
          uri: lb://PUBLICATIONS-SERVICE
          predicates:
            - Path=/publications/**

        - id: publications-likes-service
          uri: lb://PUBLICATIONS-SERVICE
          predicates:
            - Path=/likes/**

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

    gateway.discovery.locator:
      enabled: true
      lower-case-service-id: true

  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka